config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get 'signup' => 'users#new'
  get 'users' => 'users#index' # adding user list back in for testing

  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users, path: ''
  get '/:friendly_id', to: 'users#show'

  resources :sessions do
    member do
      get 'check_goodreads_authentication'
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  before_save :default_values
  def default_values
    if self.title_size.nil?
      self.title_size = '30px'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password :validations => false
  has_many :books, dependent: :destroy

  before_save :downcase_fields

  def downcase_fields
    self.name.downcase!
  end

  extend FriendlyId
  friendly_id :name, :use => :slugged, :slug_column => :name

  def slug_candidates
  [
    :name
  ]
  end

  def should_generate_new_friendly_id?
      new_record?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if (!current_user.nil?)
      redirect_to current_user
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'

    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  def check_goodreads_authentication
    # Make sure the request was authorised and we have an OAuth request token.
    # If not, return an error and have the user try again
    # TODO make this actually an error instead of sending user back to Goodreads
    if !(params[:authorize] && session[:request_token])
      respond_to do |format|
        format.html {redirect_to get_oauth_url}
      end

    else
      # Pull the request token back out of the session
      request_token = session[:request_token]
      access_token = request_token.get_access_token
      goodreads_client_oauth = Goodreads.new(oauth_token: access_token)
      goodreads_user_id = goodreads_client_oauth.user_id
      # Looks to see whether we already have an account for this Goodreads ID
      if @user = User.find_by(goodreads_id: goodreads_user_id)
        if !@user.name
          respond_to do |format|
            format.html {redirect_to edit_user_path(@user)}
          end
        else
          respond_to do |format|
            format.html {redirect_to @user}
          end
        end
      else
        @user = User.create(oauth_token: access_token, goodreads_id: goodreads_user_id)
        puts @user.name

        respond_to do |format|
          if @user.save
            log_in @user
            Bookshelf.new(@user).build_bookshelf
            format.html { redirect_to edit_user_path(@user)}
            # format.json { render :show, status: :created, location: @user }
          else
            format.html { render :new }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end

      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :add_goodreads]

  # GET /users/1
  # GET /users/1.json
  def show
  end


  # GET /users/1/edit
  def edit
    respond_to do |format|
      if @user == current_user
        format.html { render :edit }
      else
        format.html { redirect_to @user, notice: 'You are not permitted to edit this user\'s account.' }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    # TODO make sure only the logged in user can update the user.
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id].to_s.downcase)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :email, :oauth_token, :goodreads_id)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns the class that should be used for the body, if that's been set in
  # the view
  def body_class
    content_for(:body_class) || ""
  end

  # Builds and returns the URL at which a user can get authorisation for Goodreads
  def get_oauth_url
    # Build the URL to which the user will be redirected after the request token is authenticated
    callback_url = "#{check_goodreads_authentication_session_url(session)}"
    @request_token = OAuth::Consumer.new(ENV['GOODREADS_API_KEY'],ENV['GOODREADS_API_SECRET'],
      site: "http://www.goodreads.com").get_request_token

    # Put the request token in the session for use later
    session[:request_token] = @request_token
    oauth_url = @request_token.authorize_url(:oauth_callback => callback_url)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VirtualBookshelf</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.5.18/webfont.js" async></script>
  <script type="text/javascript">
    WebFontConfig = {
      google: {
        families: ['Lato','Merriweather']
      },
      active: function() {
        console.log("callback triggered");
        ready();
      }
    };
    console.log(WebFontConfig);
  </script>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
<!--%= render 'layouts/header' %-->
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <!--%= render 'layouts/footer' %-->
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/add_goodreads.html.erb
<p>Hi <%= @user.name %>!</p>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Goodreads</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.goodreads_id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% content_for :body_class do %>login_or_signup<% end %>

<h1>Last step is to choose your username and password</h1>

<%= render 'form' %>

<p>Already have an account? <%= link_to 'Log in', login_path %></p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="bookshelf group">
  <% @user.books.each do |book| %>
    <div class="book" id=<%=book.id%> style="background-color:<%=book.spine_colour%>;
    height: <%=(book.height/450)*45%>em; width: <%= book.width%>px">
      <div class="spine_text" style="color:<%=book.font_colour%>">
        <% if book.text_orientation == "rotated_all"%>
          <div class="rotate" style="width: <%=book.height%>px">
            <span class="title"><%= book.title %></span> <br/>
            <span class="author"><%= book.author %></span>
          </div>
        <% elsif  book.text_orientation == "standard"%>
          <div class="standard">
            <span class="title"><%= book.title %></span>
            <span class="author"><br/><%= book.author %></span>
          </div>
        <% end %>
      </div>
      <div class="shelf">
      </div>
    </div>
  <% end %>
</div>

<p>
  <% if logged_in? %>
    <%= link_to 'Edit your account', edit_user_path(current_user) %> |
    <%= link_to 'Log out', logout_path, method: :delete  %>
  <% else %>
    <%= link_to 'Create your own bookshelf', root_url %> |
    <%= link_to 'Log in', login_path %>
  <% end %>
</p>

app/views/welcome/index.html.erb
<h1>Sign in for your bookshelf</h1>
<p></p>